---
- hosts: camlistore
  user: root
  vars:
    config_dir: /home/camlistored/.config/camlistore
    server_config: "{{ config_dir }}/server-config.json"

  tasks:
    - name: allow ssh and camlistore
      ufw: rule=allow port={{ item }}
      with_items:
        - 22
        - 3179

    - name: deny everything and enable ufw
      ufw: state=enabled policy=deny

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400

    - name: install required packages
      apt: name={{ item }} state=installed 
      with_items:
        - golang
        - git
        - htop

    - name: download camlistore sources
      git: repo=https://camlistore.googlesource.com/camlistore dest=/usr/local/src/camlistore remote=origin version=master
      register: camlistore_repo

    - name: build camlistore
      command: go run make.go chdir=/usr/local/src/camlistore
      when: camlistore_repo.changed

    - name: copy binaries into place
      shell: cp /usr/local/src/camlistore/bin/cam* /usr/local/bin
      when: camlistore_repo.changed

    - name: create camlistored user
      user: name=camlistored

    - name: create camlistore config directory
      file: path={{ config_dir }} state=directory recurse=true
      sudo: true
      sudo_user: camlistored

    - name: make camlistored data directory
      file: path=/var/lib/camlistore state=directory owner=camlistored group=camlistored
    
    - name: add upstart config
      template: src=templates/upstart.j2 dest=/etc/init/camlistored.conf
      notify:
        - restart camlistored

    - name: get camlistore identity
      shell: "cat {{ server_config }} | grep -o 'identity\": \".*\"' | cut -c13-20"
      register: camlistore_identity

    - name: install camlistore server config
      template: src=templates/server-config.json.j2 dest={{ server_config }}
      sudo: true
      sudo_user: camlistored
      notify:
        - restart camlistored

  handlers:
    - name: restart camlistored
      service: name=camlistored state=restarted
